name: Manual UI Test

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  test_ui:
    name: Run UI Tests
    uses: ./.github/workflows/ui-test.yml
    with:
      test_branch: '${{ github.ref_name }}'
    secrets: inherit
